const D=window.UTC_DICT||{}, raw=atob(window.UTC_PACKED||''), RR=[];
for(let o=0;o<raw.length;o+=4){const v=(raw.charCodeAt(o))|(raw.charCodeAt(o+1)<<8)|(raw.charCodeAt(o+2)<<16)|(raw.charCodeAt(o+3)<<24);RR.push([v&31,(v>>>5)&63,(v>>>11)&3,(v>>>13)&3,(v>>>15)&15,(v>>>19)&3,(v>>>21)&7,(v>>>24)&3,(v>>>26)&1]);}
const publishedStudents=RR.map((r,idx)=>({i:`UTC-${String(idx+1).padStart(5,'0')}`,name:'',c:D.c[r[0]]||'',p:D.p[r[1]]||'',pe:D.pe[r[2]]||'',n:D.n[r[3]]||'',e:D.e[r[4]]||'',doc:D.do[r[5]]||'',pay:D.pa[r[6]]||'',z:D.z[r[7]]||'',ai:r[8]||0}));
let students=publishedStudents.slice(), rawRows=[], rawHeaders=[], uploadMeta=null;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)], esc=s=>(s??'').toString().replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]||c)), fmt=n=>(Number(n)||0).toLocaleString('es-MX');
const statusClass=s=>{s=(s||'').toLowerCase();if(s.includes('recuperado')||s.includes('resuelta')||s.includes('admitido'))return 'resuelta';if(s.includes('validado'))return 'validado';if(s.includes('riesgo'))return 'riesgo';if(s.includes('baja'))return 'baja';if(s.includes('revision'))return 'revision';if(s.includes('soporte'))return 'soporte';if(s.includes('ajuste'))return 'ajuste';if(s.includes('nueva')||s.includes('pend'))return 'nueva';return ''};
const campuses=()=>[...new Set(students.map(x=>x.c).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'es'));
const isRecovery=x=>{const s=(x?.e||'').toLowerCase();return s==='baja'||s.includes('riesgo de baja')||s.includes('en riesgo')};
const params=new URLSearchParams(location.search);let role=['manager','commercial','campus'].includes(params.get('view'))?params.get('view'):'campus', selectedCampus=params.get('campus')||campuses()[0]||'', currentView='', selected=null, modalMode='normal';
function countBy(arr,key){const o={};arr.forEach(x=>{const k=x[key]||'Sin dato';o[k]=(o[k]||0)+1});return o}function todayRef(){return new Date()}function ageDays(t){return Math.max(0,(todayRef()-new Date(t.created))/86400000)}
function buildSeed(){const cs=campuses(), stat=['NUEVA','EN REVISIÓN','EN REVISIÓN','AJUSTE CI','SOPORTE','RESUELTA','RESUELTA'], types=['Admisión','Validación','Cambio de ciclo','Documentos','Pago','Accesos'];let out=[];for(let i=0;i<50;i++){const c=cs[(i*5+2)%Math.max(1,cs.length)],stu=students[(i*91)%students.length],s=stat[i%stat.length];out.push({id:2101+i,matricula:stu?.i||'',campus:c,tipo:types[(i*3)%types.length],descripcion:'Seguimiento de prueba para validar el flujo.',area:'Campus',estatus:s,responsable:s==='RESUELTA'?'Onboarding':'',created:`2026-08-${String(1+i%8).padStart(2,'0')}T10:00:00`,updated:new Date().toISOString(),demo:true})}const rec=students.filter(isRecovery).slice(0,18);rec.forEach((stu,i)=>out.push({id:3001+i,matricula:stu.i,campus:stu.c,tipo:'Recuperación',descripcion:['Primer contacto','Segundo intento','Alumno solicita llamada posterior','Validar opción de recuperación'][i%4],area:'Comercial',estatus:i%5===0?'RESUELTA':'EN REVISIÓN',resultado:i%5===0?'RECUPERADO':['PENDIENTE','CONTACTADO','SIN CONTACTO','EN NEGOCIACIÓN'][i%4],responsable:'Comercial',created:`2026-08-${String(2+i%7).padStart(2,'0')}T11:00:00`,updated:new Date().toISOString(),demo:true}));return out}
function getF(){try{const x=JSON.parse(localStorage.getItem('utc_sept_followups_v4')||'null');if(Array.isArray(x)&&x.length)return x}catch{}const x=buildSeed();localStorage.setItem('utc_sept_followups_v4',JSON.stringify(x));return x}function setF(x){localStorage.setItem('utc_sept_followups_v4',JSON.stringify(x))}
function setRole(r){role=r;const u=new URL(location.href);u.searchParams.set('view',r);history.replaceState({},'',u);$$('.roleBtn').forEach(b=>b.classList.toggle('active',b.dataset.role===r));renderSidebar();showView(r==='manager'?'managerDashboard':r==='commercial'?'commercialHome':'campusHome')}
function renderSidebar(){let items,label;if(role==='manager'){label='Gestión';items=[['managerDashboard','▦ Dashboard'],['managerFollowups','◎ Seguimientos'],['managerData','▤ Visualizador de datos'],['studentsView','⌕ Consulta operativa'],['managerUpload','⇧ Cargar Salesforce']]}else if(role==='commercial'){label='Comercial';items=[['commercialHome','▦ Recuperación'],['commercialPortfolio','⌕ Bajas y riesgos'],['commercialFollowups','◎ Mis gestiones']]}else{label='Campus';items=[['campusHome','⌂ Inicio'],['studentsView','⌕ Consultar alumno'],['campusFollowups','◎ Mis seguimientos']]}$('#sidebar').innerHTML=`<div class="sideLabel">${label}</div>`+items.map(([v,l])=>`<button class="nav ${currentView===v?'active':''}" data-view="${v}">${l}</button>`).join('');$$('#sidebar .nav').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.view)))}
function showView(v){currentView=v;$$('.view').forEach(x=>x.classList.add('hidden'));$('#'+v).classList.remove('hidden');renderSidebar();({campusHome:renderCampusHome,studentsView:renderStudents,campusFollowups:renderCampusF,commercialHome:renderCommercialHome,commercialPortfolio:renderCommercialPortfolio,commercialFollowups:renderCommercialF,managerDashboard:renderManagerDash,managerFollowups:renderManagerF,managerData:renderManagerData,managerUpload:renderUpload}[v]||(()=>{}))()}
function campusSelect(id,val){return `<select id="${id}">${campuses().map(c=>`<option ${c===val?'selected':''}>${esc(c)}</option>`).join('')}</select>`}
function renderCampusHome(){const t=getF().filter(x=>x.area!=='Comercial'&&x.campus===selectedCampus),open=t.filter(x=>x.estatus!=='RESUELTA').length;$('#campusHome').innerHTML=`<div class="campusHero"><div><h2>Portal del plantel</h2><div class="sub">Consulta al alumno y genera un seguimiento en pocos pasos.</div></div><div class="campusChooser"><label>Simular plantel</label>${campusSelect('campSel',selectedCampus)}</div></div><div class="metrics"><div class="metric"><span class="sub">Seguimientos</span><b>${fmt(t.length)}</b></div><div class="metric"><span class="sub">En proceso</span><b>${fmt(open)}</b></div><div class="metric"><span class="sub">Resueltos</span><b>${fmt(t.length-open)}</b></div><div class="metric"><span class="sub">Alumnos del plantel</span><b>${fmt(students.filter(x=>x.c===selectedCampus).length)}</b></div></div><div class="panel"><h3 style="margin-top:0">¿Qué necesitas hacer?</h3><button class="btn primary" id="goSearch">Buscar alumno</button> <button class="btn" id="quickFollow">Crear seguimiento</button></div>`;$('#campSel').addEventListener('change',e=>{selectedCampus=e.target.value;renderCampusHome()});$('#goSearch').onclick=()=>showView('studentsView');$('#quickFollow').onclick=()=>openFollow()}
function renderStudents(){const base=role==='campus'?students.filter(x=>x.c===selectedCampus):students,cs=role==='campus'?[selectedCampus]:campuses(),statuses=[...new Set(base.map(x=>x.e).filter(Boolean))].sort(),periods=[...new Set(base.map(x=>x.pe).filter(Boolean))].sort();$('#studentsView').innerHTML=`<h2>${role==='manager'?'Consulta operativa':'Consultar alumno'}</h2><div class="filters"><div><label>Buscar</label><input id="q" placeholder="Matrícula, alumno, programa..."></div><div><label>Plantel</label><select id="sc" ${role==='campus'?'disabled':''}>${role==='manager'?'<option value="">Todos</option>':''}${cs.map(c=>`<option>${esc(c)}</option>`).join('')}</select></div><div><label>Estatus</label><select id="ss"><option value="">Todos</option>${statuses.map(s=>`<option>${esc(s)}</option>`).join('')}</select></div><div><label>Periodo</label><select id="sp"><option value="">Todos</option>${periods.map(s=>`<option>${esc(s)}</option>`).join('')}</select></div></div><div class="students"><div class="tablewrap"><table><thead><tr><th>${students===publishedStudents?'ID prueba':'Matrícula'}</th>${students.some(x=>x.name)?'<th>Alumno</th>':''}<th>Plantel</th><th>Programa</th><th>Periodo</th><th>Estatus</th></tr></thead><tbody id="sb"></tbody></table></div><div class="panel studentcard" id="studentCard"><div class="sub">Selecciona un registro.</div></div></div>`;if(role==='campus')$('#sc').value=selectedCampus;const apply=()=>{const q=$('#q').value.toLowerCase(),c=$('#sc').value,s=$('#ss').value,p=$('#sp').value;let f=base.filter(x=>(!c||x.c===c)&&(!s||x.e===s)&&(!p||x.pe===p)&&(!q||[x.i,x.name,x.c,x.p,x.e].some(v=>String(v||'').toLowerCase().includes(q))));$('#sb').innerHTML=f.slice(0,500).map(x=>`<tr class="click" data-id="${esc(x.i)}"><td><b>${esc(x.i)}</b></td>${students.some(y=>y.name)?`<td>${esc(x.name)}</td>`:''}<td>${esc(x.c)}</td><td>${esc(x.p)}</td><td>${esc(x.pe)}</td><td><span class="pill ${statusClass(x.e)}">${esc(x.e)}</span></td></tr>`).join('');$$('#sb .click').forEach(r=>r.onclick=()=>showStudent(r.dataset.id))};['q','sc','ss','sp'].forEach(id=>$('#'+id).addEventListener(id==='q'?'input':'change',apply));apply()}
function showStudent(id){selected=students.find(x=>String(x.i)===String(id));if(!selected)return;const x=selected;$('#studentCard').innerHTML=`<h3 style="margin-top:0">${esc(x.name||x.i)}</h3><div class="sub">${x.name?esc(x.i):'Identidad protegida en publicación pública'}</div><div class="facts"><div class="fact"><small>Plantel</small>${esc(x.c)}</div><div class="fact"><small>Estatus</small><span class="pill ${statusClass(x.e)}">${esc(x.e)}</span></div><div class="fact"><small>Periodo</small>${esc(x.pe)}</div><div class="fact"><small>Pago</small>${esc(x.pay)}</div><div class="fact"><small>Documentos</small>${esc(x.doc)}</div><div class="fact"><small>Zona</small>${esc(x.z)}</div></div><div class="fact"><small>Programa</small>${esc(x.p)}</div><button class="btn primary" style="width:100%;margin-top:12px" id="studentFollow">Crear seguimiento</button>`;$('#studentFollow').onclick=()=>openFollow(x.i,x.c)}
function followCard(x,manage=false){return `<div class="followup" data-fid="${x.id}"><div class="followhead"><div><b>#${x.id} · ${esc(x.tipo)}</b><div class="sub">${esc(x.campus)} · ${esc(x.matricula)}</div></div><span class="pill ${statusClass(x.estatus)}">${esc(x.estatus)}</span></div><p>${esc(x.descripcion)}</p><div class="followmeta">${x.resultado?`<span class="pill ${statusClass(x.resultado)}">${esc(x.resultado)}</span>`:''}<span class="sub">${new Date(x.created).toLocaleDateString('es-MX')}</span>${x.responsable?`<span class="sub">Responsable: ${esc(x.responsable)}</span>`:''}</div>${manage?`<div class="followActions"><div><label>Estatus</label><select class="fst">${['NUEVA','EN REVISIÓN','AJUSTE CI','SOPORTE','RESUELTA'].map(s=>`<option ${s===x.estatus?'selected':''}>${s}</option>`).join('')}</select></div><div><label>Responsable</label><input class="fow" value="${esc(x.responsable||'')}"></div><button class="btn saveChange" data-id="${x.id}">Guardar</button></div>`:''}</div>`}
function renderCampusF(){const t=getF().filter(x=>x.area!=='Comercial'&&x.campus===selectedCampus).reverse();$('#campusFollowups').innerHTML=`<div class="campusHero"><div><h2>Mis seguimientos</h2><div class="sub">Plantel ${esc(selectedCampus)}</div></div><button class="btn primary" id="newCampusF">+ Seguimiento</button></div><div class="followups" style="margin-top:14px">${t.map(x=>followCard(x)).join('')||'<div class="panel empty">Sin seguimientos.</div>'}</div>`;$('#newCampusF').onclick=()=>openFollow()}
function recoveryStudents(){return students.filter(isRecovery)}
