function renderCommercialHome(){const r=recoveryStudents(),b=r.filter(x=>(x.e||'').toLowerCase()==='baja'),risk=r.filter(x=>(x.e||'').toLowerCase().includes('riesgo')),f=getF().filter(x=>x.area==='Comercial'),rec=f.filter(x=>x.resultado==='RECUPERADO').length,by=countBy(r,'c'),top=Object.entries(by).sort((a,b)=>b[1]-a[1]).slice(0,10),mx=Math.max(1,...top.map(x=>x[1]));$('#commercialHome').innerHTML=`<h2>Recuperación comercial</h2><div class="sub">Sólo alumnos en Baja o En riesgo de baja.</div><div class="metrics"><div class="metric"><span class="sub">Cartera a recuperar</span><b>${fmt(r.length)}</b></div><div class="metric"><span class="sub">Bajas</span><b>${fmt(b.length)}</b></div><div class="metric"><span class="sub">Riesgo de baja</span><b>${fmt(risk.length)}</b></div><div class="metric"><span class="sub">Recuperados en demo</span><b>${fmt(rec)}</b></div></div><div class="two"><div class="panel"><h3 style="margin-top:0">Casos por plantel</h3><div class="barRows">${top.map(([k,v])=>`<div class="barRow"><span>${esc(k)}</span><div class="barTrack"><div class="barFill bad" style="width:${v/mx*100}%"></div></div><b>${v}</b></div>`).join('')}</div></div><div class="panel"><h3 style="margin-top:0">Acción rápida</h3><p class="sub">Abre la cartera, selecciona un alumno y registra la gestión.</p><button class="btn primary" id="goRecovery">Ver bajas y riesgos</button></div></div>`;$('#goRecovery').onclick=()=>showView('commercialPortfolio')}
function renderCommercialPortfolio(){const base=recoveryStudents(),cs=[...new Set(base.map(x=>x.c))].sort();$('#commercialPortfolio').innerHTML=`<h2>Bajas y riesgos de baja</h2><div class="sub">Cartera disponible para recuperación.</div><div class="filters" style="grid-template-columns:2fr 1fr 1fr"><div><label>Buscar</label><input id="rq" placeholder="Matrícula, alumno, programa..."></div><div><label>Plantel</label><select id="rc"><option value="">Todos</option>${cs.map(c=>`<option>${esc(c)}</option>`).join('')}</select></div><div><label>Estatus</label><select id="rs"><option value="">Todos</option><option>Baja</option><option>En riesgo de baja</option></select></div></div><div class="panel" id="recoveryList"></div>`;const apply=()=>{const q=$('#rq').value.toLowerCase(),c=$('#rc').value,s=$('#rs').value;const f=base.filter(x=>(!c||x.c===c)&&(!s||x.e===s)&&(!q||[x.i,x.name,x.c,x.p,x.e].some(v=>String(v||'').toLowerCase().includes(q))));$('#recoveryList').innerHTML=f.slice(0,500).map(x=>`<div class="recoveryRow"><div><b>${esc(x.name||x.i)}</b><div class="sub">${esc(x.i)}</div></div><div>${esc(x.c)}</div><div>${esc(x.p)}</div><div><span class="pill ${statusClass(x.e)}">${esc(x.e)}</span></div><button class="btn primary recoveryBtn" data-id="${esc(x.i)}">Gestionar</button></div>`).join('')||'<div class="empty">Sin resultados.</div>';$$('.recoveryBtn').forEach(b=>b.onclick=()=>{const x=students.find(s=>String(s.i)===String(b.dataset.id));openFollow(x.i,x.c,'recovery')})};['rq','rc','rs'].forEach(id=>$('#'+id).addEventListener(id==='rq'?'input':'change',apply));apply()}
function renderCommercialF(){const t=getF().filter(x=>x.area==='Comercial').reverse();$('#commercialFollowups').innerHTML=`<h2>Gestiones de recuperación</h2><div class="sub">Historial de acciones comerciales.</div><div class="followups" style="margin-top:14px">${t.map(x=>followCard(x)).join('')||'<div class="panel empty">Sin gestiones.</div>'}</div>`}
function renderManagerDash(){const t=getF(),open=t.filter(x=>x.estatus!=='RESUELTA'),res=t.filter(x=>x.estatus==='RESUELTA'),byC=countBy(t,'campus'),byS=countBy(t,'estatus'),byT=countBy(t,'tipo'),top=Object.entries(byC).sort((a,b)=>b[1]-a[1]).slice(0,10),mx=Math.max(1,...top.map(x=>x[1])),over=open.filter(x=>ageDays(x)>=3),ss=countBy(students,'e'),recovery=recoveryStudents();$('#managerDashboard').innerHTML=`<h2>Dashboard de gestión</h2><div class="sub">Seguimientos + estado de la base Salesforce.</div><div class="metrics"><div class="metric"><span class="sub">Seguimientos totales</span><b>${fmt(t.length)}</b></div><div class="metric"><span class="sub">En espera / proceso</span><b>${fmt(open.length)}</b><small>${over.length} con 3+ días</small></div><div class="metric"><span class="sub">Resueltos</span><b>${fmt(res.length)}</b><small>${Math.round(res.length/Math.max(1,t.length)*100)}% resolución</small></div><div class="metric"><span class="sub">Bajas + riesgos</span><b>${fmt(recovery.length)}</b><small>Cartera comercial</small></div></div><div class="three"><div class="panel"><h3 style="margin-top:0">Seguimientos por plantel</h3><div class="barRows">${top.map(([k,v])=>`<div class="barRow"><span>${esc(k)}</span><div class="barTrack"><div class="barFill" style="width:${v/mx*100}%"></div></div><b>${v}</b></div>`).join('')}</div></div><div class="panel"><h3 style="margin-top:0">Por estatus</h3><div class="listRows">${Object.entries(byS).sort((a,b)=>b[1]-a[1]).map(([k,v])=>`<div class="listRow"><span>${esc(k)}</span><b>${v}</b></div>`).join('')}</div></div><div class="panel"><h3 style="margin-top:0">Por tipo</h3><div class="listRows">${Object.entries(byT).sort((a,b)=>b[1]-a[1]).slice(0,8).map(([k,v])=>`<div class="listRow"><span>${esc(k)}</span><b>${v}</b></div>`).join('')}</div></div></div><div class="two" style="margin-top:14px"><div class="panel"><h3 style="margin-top:0">Corte Salesforce</h3><div class="baseMeta"><div class="fact"><small>Registros</small><b>${fmt(students.length)}</b></div><div class="fact"><small>Admitidos</small><b>${fmt(ss.Admitido||0)}</b></div><div class="fact"><small>Validados</small><b>${fmt(ss.Validado||0)}</b></div><div class="fact"><small>Bajas</small><b>${fmt(ss.Baja||0)}</b></div></div><div class="sub" style="margin-top:10px">${uploadMeta?`Cargado: ${esc(uploadMeta.name)} · ${esc(uploadMeta.when)}`:'Base pública operativa enmascarada.'}</div></div><div class="panel"><h3 style="margin-top:0">Atención prioritaria</h3><div class="listRows">${over.sort((a,b)=>ageDays(b)-ageDays(a)).slice(0,6).map(x=>`<div class="listRow"><span>#${x.id} · ${esc(x.campus)} · ${esc(x.tipo)}</span><b>${Math.floor(ageDays(x))} d</b></div>`).join('')||'<span class="sub">Sin seguimientos vencidos.</span>'}</div></div></div>`}
function renderManagerF(){
 const t=getF().reverse();
 $('#managerFollowups').innerHTML=`<div class="campusHero"><div><h2>Todos los seguimientos</h2><div class="sub">Onboarding y recuperación comercial.</div></div><button class="btn primary" id="managerNew">+ Seguimiento</button></div><div class="filters"><div><label>Buscar</label><input id="fq"></div><div><label>Plantel</label><select id="fcp"><option value="">Todos</option>${campuses().map(c=>`<option>${esc(c)}</option>`).join('')}</select></div><div><label>Área</label><select id="far"><option value="">Todas</option><option>Campus</option><option>Comercial</option><option>Gestor</option></select></div><div><label>Estatus</label><select id="fes"><option value="">Todos</option>${['NUEVA','EN REVISIÓN','AJUSTE CI','SOPORTE','RESUELTA'].map(s=>`<option>${s}</option>`).join('')}</select></div></div><div class="followups" id="managerList"></div>`;
 $('#managerNew').onclick=()=>openFollow();
 const apply=()=>{
   const q=$('#fq').value.toLowerCase(), c=$('#fcp').value, a=$('#far').value, st=$('#fes').value;
   const f=t.filter(x=>{
     const matchesText=!q || JSON.stringify(x).toLowerCase().includes(q);
     return (!c||x.campus===c) && (!a||x.area===a) && (!st||x.estatus===st) && matchesText;
   });
   $('#managerList').innerHTML=f.map(x=>followCard(x,true)).join('')||'<div class="panel empty">Sin resultados.</div>';
   $$('.saveChange').forEach(b=>b.onclick=()=>saveChange(Number(b.dataset.id)));
 };
 ['fq','fcp','far','fes'].forEach(id=>$('#'+id).addEventListener(id==='fq'?'input':'change',apply));
 apply();
}
function saveChange(id){const t=getF(),x=t.find(y=>Number(y.id)===id),card=$(`[data-fid="${id}"]`);if(!x||!card)return;x.estatus=card.querySelector('.fst').value;x.responsable=card.querySelector('.fow').value.trim();x.updated=new Date().toISOString();setF(t);renderManagerF()}
